export default {
	REDUX_STORE_EVENTS: {

		SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
		RESET_ALERTS: 'RESET_ALERTS',

		SET_ITEMS: 'SET_ITEMS',
		SET_ITEM_DETAILS: 'SET_ITEM_DETAILS',
		RESET_ITEM_DETAILS: 'RESET_ITEM_DETAILS'
	}
};
